// Command floorplanseed generates the migration that seeds
// packages/floorplans into carepath.floor_plan.
//
// It exists because migration 000008 says its INSERTs were "generated from
// that JSON by script" and that script was never committed — so changing the
// map since then has meant hand-writing SQL against data that already has a
// source of truth. This one is committed, and `make seed-floorplans`
// regenerates its output.
//
// The SVG is put through internal/floorplan on the way in, so a seeded plan
// is byte-identical to what uploading the same file would store: same
// normalization, same digest, same URL.
//
// Usage:
//
//	go run ./cmd/floorplanseed > ../../infra/postgres/migrations/000024_seed_floor_plans.up.sql
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"carepath/apps/api/internal/floorplan"
)

// The floors that ship with the repo, in display order. A new floor is added
// here and the migration regenerated.
var shipped = []struct {
	floorID string
	file    string
}{
	{"I-1301", "i-1301-ground.svg"},
	{"I-1302", "i-1302-upper.svg"},
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "floorplanseed:", err)
		os.Exit(1)
	}
}

func run() error {
	var b strings.Builder
	b.WriteString(`-- #105 / ADR-0015: the plans from packages/floorplans as the first
-- floor_plan rows, so the app has a plan to serve before any admin uploads
-- one. Generated by apps/api/cmd/floorplanseed — do not hand-edit; run
-- ` + "`make seed-floorplans`" + ` after changing a floor-plan asset.
--
-- Each svg below is internal/floorplan's output for the committed file, so a
-- seeded plan is indistinguishable from the same file uploaded through the
-- admin API. created_by is NULL: no admin uploaded these.

`)

	for _, floor := range shipped {
		path := filepath.Join("..", "..", "packages", "floorplans", "floors", floor.file)
		src, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		plan, err := floorplan.Normalize(src, floorplan.Expect{FloorID: floor.floorID})
		if err != nil {
			return fmt.Errorf("%s: %w", floor.file, err)
		}
		// Warnings are deliberately not computed here. They are a comparison
		// against the live place and nav_node rows, which this generator
		// cannot see and which the migration order does not guarantee yet;
		// the upload path and the plan health view do that reconciliation
		// against the real model.

		planID := floorplan.PlanIDFor(floor.floorID, plan.SHA256)
		fmt.Fprintf(&b, "INSERT INTO carepath.floor_plan (plan_id, floor_id, sha256, viewbox, svg, svg_raw)\nVALUES (%s, %s, %s, %s, %s, %s)\nON CONFLICT (plan_id) DO NOTHING;\n\n",
			quote(planID), quote(floor.floorID), quote(plan.SHA256), quote(plan.ViewBox),
			quote(plan.SVG), quote(string(src)))
		// AND active_plan_id IS NULL: only ever sets the floor's very first
		// plan. Without it, re-running this migration (or applying it to a
		// database an admin has already uploaded to) would silently point
		// the floor back at the seed, discarding a live upload with no error
		// anywhere.
		fmt.Fprintf(&b, "UPDATE carepath.floor SET viewbox = %s, active_plan_id = %s WHERE floor_id = %s AND active_plan_id IS NULL;\n\n",
			quote(plan.ViewBox), quote(planID), quote(floor.floorID))
	}

	_, err := os.Stdout.WriteString(b.String())
	return err
}

// quote writes a Postgres dollar-quoted literal. The plans contain single
// quotes (CSS font stacks) and the tag keeps the SQL readable instead of
// doubling every one of them.
func quote(s string) string {
	tag := "$plan$"
	for strings.Contains(s, tag) {
		tag = "$" + tag
	}
	return tag + s + tag
}
