package postgres

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"os"
	"testing"

	"carepath/apps/api/internal/floorplan"
	"carepath/apps/api/internal/platform/db"
)

// Integration test against a real Postgres. Requires the schema and seed
// data from infra/postgres/migrations; run `make migrate-up` first.
func newDB(t *testing.T) *db.DB {
	t.Helper()
	databaseURL := os.Getenv("DATABASE_URL")
	if databaseURL == "" {
		t.Skip("DATABASE_URL not set; skipping integration test (run make up / migrate-up first)")
	}
	database, err := db.New(context.Background(), databaseURL)
	if err != nil {
		t.Fatalf("connect: %v", err)
	}
	t.Cleanup(database.Close)
	return database
}

// The seeded ground-floor plan, from migration 000024 (generated by
// cmd/floorplanseed out of packages/floorplans).
const (
	groundFloorID  = "I-1301"
	groundFloorSHA = "b6c8f46935f1fef6beb61a098d615dcbbf9c3ef5514cb45e8683a6525b979324"
	groundPlanID   = "FP-I1301-" + groundFloorSHA
)

// The digest in the URL is a promise that the bytes behind it are exactly
// that content. This checks the promise against the database rather than
// against the seeding code that made it.
func TestSVGMatchesItsDigest(t *testing.T) {
	repo := New(newDB(t))

	svg, err := repo.SVG(context.Background(), groundFloorID, groundFloorSHA)
	if err != nil {
		t.Fatalf("SVG: %v", err)
	}
	digest := sha256.Sum256([]byte(svg))
	if got := hex.EncodeToString(digest[:]); got != groundFloorSHA {
		t.Errorf("stored plan hashes to %s, but is addressed as %s", got, groundFloorSHA)
	}

	// Normalizing a stored plan must be a no-op: it went through the
	// normalizer on the way in, so anything that changed here would mean the
	// pipeline is not stable across a round trip through Postgres.
	plan, err := floorplan.Normalize([]byte(svg), floorplan.Expect{FloorID: groundFloorID, ViewBox: "0 0 1600 900"})
	if err != nil {
		t.Fatalf("stored plan no longer normalizes: %v", err)
	}
	if plan.SHA256 != groundFloorSHA {
		t.Errorf("re-normalized digest = %s, want %s", plan.SHA256, groundFloorSHA)
	}
}

// A digest is only valid on the floor it was stored for: the URL carries
// both, and one floor's link must not reach another floor's drawing.
func TestSVGIsScopedToItsFloor(t *testing.T) {
	repo := New(newDB(t))

	if _, err := repo.SVG(context.Background(), "I-1302", groundFloorSHA); err != floorplan.ErrPlanNotFound {
		t.Errorf("err = %v, want ErrPlanNotFound", err)
	}
	if _, err := repo.SVG(context.Background(), groundFloorID, "deadbeef"); err != floorplan.ErrPlanNotFound {
		t.Errorf("err = %v, want ErrPlanNotFound", err)
	}
}

func TestDigests(t *testing.T) {
	repo := New(newDB(t))

	digests, err := repo.Digests(context.Background(), []string{groundPlanID, "FP-NOPE"})
	if err != nil {
		t.Fatalf("Digests: %v", err)
	}
	if digests[groundPlanID] != groundFloorSHA {
		t.Errorf("digest for %s = %q, want %s", groundPlanID, digests[groundPlanID], groundFloorSHA)
	}
	// An unknown plan id is simply absent — the floors listing then omits
	// planUrl rather than handing out a URL that would 404.
	if _, ok := digests["FP-NOPE"]; ok {
		t.Error("an unknown plan id came back with a digest")
	}
}
