// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/analytics/overview": {
            "get": {
                "description": "Operational metrics for the executive dashboard (#86): per-service-point wait/service numbers and visit-wide summary, aggregated in SQL from the append-only step timeline (#85). window=today means midnight-to-now in the analytics timezone (Asia/Bangkok by default). Executives get EXECUTIVE logins that reach this surface and nothing else (ADR-0010); no patient-level data (NFR-03).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get the executive analytics overview",
                "parameters": [
                    {
                        "enum": [
                            "today"
                        ],
                        "type": "string",
                        "description": "Aggregation window; only \\",
                        "name": "window",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/analytics.Overview"
                        }
                    },
                    "400": {
                        "description": "unsupported window",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "missing, malformed, or expired staff access token",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "authenticated, but the user's roles do not allow this action",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Verifies a username against an argon2id password hash and returns a short-lived JWT access token plus a rotating opaque refresh token. Unknown username, wrong password, and deactivated account are deliberately indistinguishable (same 401 body, same timing).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Staff/admin login",
                "parameters": [
                    {
                        "description": "username and password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.tokensResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "description": "Revokes the presented refresh token. Idempotent — an unknown, expired or already-revoked token also returns 204, so a client can always clear its own state.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log out",
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/me": {
            "get": {
                "description": "The staff/admin identity and role codes behind the presented access token. The console calls it on boot to restore a session from a stored refresh token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "The current staff identity",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.identityResponse"
                        }
                    },
                    "401": {
                        "description": "missing, malformed, or expired access token",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Exchanges a refresh token for a new access + refresh pair; the presented token is spent. Presenting an already-spent token is treated as a leak: every refresh token of that user is revoked and the call returns 401.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh the token pair",
                "parameters": [
                    {
                        "description": "the refresh token issued by login or a previous refresh",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.refreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.tokensResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "unknown, expired, revoked, or already-spent refresh token",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/session": {
            "get": {
                "description": "Resolves the Authorization: Bearer session token to the identity behind it.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get the current session identity",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.identityResponse"
                        }
                    },
                    "401": {
                        "description": "session not found or expired",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Exchanges a LINE ID token (or, when enabled, a demo identity) for an opaque CarePath session token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Create a patient session",
                "parameters": [
                    {
                        "description": "source: line|demo, idToken: the LINE ID token (ignored for demo)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.createRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.createResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "invalid identity token, or demo auth disabled",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/demo/zigbee/location": {
            "post": {
                "description": "Demo-only simulator for the Zigbee positioning service (#33): reports a zone-level fix for the visit through the canonical ZIGBEE location provider and returns the recorded observation. The zone resolves to its representative navigation node, which becomes the routing start point like any other location. A real Zigbee integration will consume positioning-service pushes through a separate adapter, not this endpoint.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Simulate a Zigbee zone fix",
                "parameters": [
                    {
                        "description": "Simulated zone fix: visitId, floorId, zone, optional confidence",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/location.zigbeeSimulatorRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/location.Observation"
                        }
                    },
                    "400": {
                        "description": "invalid body, or a floor/zone that does not resolve to a known location",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/journeys/{visitId}": {
            "get": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "description": "Returns the CarePath-derived journey plan (ADR-0009): steps in display order, each resolved to its service point, with every currently-actionable step and CarePath's recommendation among them. A completed visit is reported with completed=true and no actionable steps. Patient-surface (#96): the patient session's identity must have claimed this visit; an unclaimed or unknown visit answers the same 404.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "journeys"
                ],
                "summary": "Get the patient journey",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit ID",
                        "name": "visitId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/journey.View"
                        }
                    },
                    "401": {
                        "description": "missing or invalid patient session",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "visit unknown, or not claimed by this session — indistinguishable",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/journeys/{visitId}/claim": {
            "post": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "description": "Records that the identity behind the patient session owns the visit (#96) — the only way read access to a journey is minted. Knowing the VN is the credential, matching the product's patient front door. Idempotent: re-claiming a visit already owned by this identity succeeds. A visit that was never projected answers 404, indistinguishable from the journey read's unknown-visit 404.",
                "tags": [
                    "auth"
                ],
                "summary": "Claim a visit for this session's identity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit id",
                        "name": "visitId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "401": {
                        "description": "missing or invalid patient session",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "visit not projected",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/journeys/{visitId}/clinics/{clinicCode}/close-round": {
            "post": {
                "description": "Staff override (ADR-0009 §4): confirms the visit's latest round at this clinic is finished, dropping any not-yet-started inferred return, without waiting for the HIS's encounter.completed fact.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "journeys"
                ],
                "summary": "Close a clinic round",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit ID",
                        "name": "visitId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Clinic code",
                        "name": "clinicCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/journey.View"
                        }
                    },
                    "404": {
                        "description": "visit not found, journey not projected, or no open round at this clinic",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/journeys/{visitId}/location": {
            "get": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "description": "The latest recorded location observation of the visit (QR scan, Zigbee fix, manual pick) — the canonical start point for routing. Patient-surface (#96): the session must have claimed the visit.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Get the visit's current location",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit ID",
                        "name": "visitId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/location.Observation"
                        }
                    },
                    "401": {
                        "description": "missing or invalid patient session",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "no location recorded yet, visit unknown, or not claimed by this session",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "description": "Records a location fix for the visit and makes it the current location. The raw payload is the scanned string (a CarePath location QR carries a place reference only — never patient data); the server resolves it through the matching provider to a canonical navigation node and returns the recorded observation. Patient-surface (#96): the session must have claimed the visit.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Report a scanned location fix",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit ID",
                        "name": "visitId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Scanned fix: source (e.g. QR) and raw payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/location.reportRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/location.Observation"
                        }
                    },
                    "400": {
                        "description": "invalid body, unknown source, or a fix that does not resolve to a known location",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "missing or invalid patient session",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "visit unknown, or not claimed by this session — indistinguishable",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/journeys/{visitId}/queue": {
            "get": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "description": "FR-17: for every currently-actionable step bound to a service point, how many people are waiting ahead of this patient there right now, and that point's average experienced wait so far today. Averages over zero samples are null, not 0 — \"no data yet\" and \"zero minutes\" are different facts, and the client must not render a guess. estimatedWaitMinutes is the naive product of the two, null whenever the average is null. Patient-surface (#96): the session's identity must have claimed this visit; an unclaimed or unknown visit answers the same 404 as the journey read.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "journeys"
                ],
                "summary": "Get the patient queue picture for the next steps",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit ID",
                        "name": "visitId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/journey.QueueView"
                        }
                    },
                    "401": {
                        "description": "missing or invalid patient session",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "visit unknown, or not claimed by this session — indistinguishable",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/journeys/{visitId}/share": {
            "post": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "description": "Mints a read-only, time-limited link token (ADR-0011). Returns the raw token exactly once — store sha256 only — plus its expiry. The response carries no URL: the web app composes /shared#\u003ctoken\u003e itself so the API never needs its own origin. At most 5 active links per visit (409 beyond).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "share"
                ],
                "summary": "Create a relative share link for a visit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit id",
                        "name": "visitId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/share.LinkSecret"
                        }
                    },
                    "401": {
                        "description": "missing or invalid patient session",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "visit not projected",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "active-link cap reached",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "description": "Revokes every still-active share link of the visit. Idempotent — 204 whether or not any link existed.",
                "tags": [
                    "share"
                ],
                "summary": "Stop sharing a visit (\"หยุดแชร์\")",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit id",
                        "name": "visitId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "401": {
                        "description": "missing or invalid patient session",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/journeys/{visitId}/steps/{stepKey}/transition": {
            "post": {
                "description": "Staff command that sets one step's status directly (ADR-0009 — CarePath owns step status; never forwarded to the HIS) and returns the refreshed journey with the plan recomputed. commandId is an optional idempotency key; source names the acting surface for the audit trail.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "journeys"
                ],
                "summary": "Transition one step",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit ID",
                        "name": "visitId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Step key",
                        "name": "stepKey",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Transition command",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/journey.transitionRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/journey.View"
                        }
                    },
                    "400": {
                        "description": "invalid body or unknown target status",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "visit or step not found, or journey not projected",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "illegal transition",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "upstream HIS error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/navigation/route": {
            "get": {
                "description": "Shortest walkable route for the SVG overlay. from is the current location's navigation node id — the nodeId of a location observation (e.g. I-1301/node-reception); to is the destination service point's code, which the server resolves to the place's entry node before routing.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "navigation"
                ],
                "summary": "Get the walking route to a service point",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Current location node id (e.g. I-1301/node-reception)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Destination service point code (e.g. PHARMACY)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Skip non-accessible edges (stairs) so the route detours via the elevator (FR-20)",
                        "name": "accessibleOnly",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/navigation.Route"
                        }
                    },
                    "400": {
                        "description": "missing from or to, or accessibleOnly is not a boolean",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "unknown node or service point, destination without a mapped place, or no walkable path",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/service-points": {
            "get": {
                "description": "Active service points with their resolved place and floor — the service → destination mapping patients navigate by and staff see in the console.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service-points"
                ],
                "summary": "List service points",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/servicepoint.ServicePoint"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/service-points/{code}": {
            "get": {
                "description": "One active service point (e.g. code LAB) with its resolved place and floor — the destination lookup for a care step's service code.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service-points"
                ],
                "summary": "Get a service point by code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service code (e.g. REGISTRATION, DOCTOR, LAB, XRAY, PHARMACY)",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/servicepoint.ServicePoint"
                        }
                    },
                    "404": {
                        "description": "service point not found",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/shared/journey": {
            "get": {
                "security": [
                    {
                        "shareAuth": []
                    }
                ],
                "description": "Resolves the share token (Authorization: Bearer) to the redacted SharedJourney — current step as Thai text, coarse status, service point name and floor, nothing else (ADR-0011 §3). Unknown, expired, and revoked tokens all answer with the same 401.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "share"
                ],
                "summary": "Read the journey a share link points to",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/share.SharedJourney"
                        }
                    },
                    "401": {
                        "description": "invalid, expired, or revoked share token",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/staff/planning-rules": {
            "get": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "description": "FR-13/US-16: the rules the planner actually runs on — the phase ladder (ADR-0009 §3), the order-type → step-kind mapping, and worked examples computed by the real Plan function. Read-only: editing rules is a code change, not a request. Codes only (ADR-0012); display text lives in the client.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "Get the journey planning rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/journey.PlanningRules"
                        }
                    },
                    "401": {
                        "description": "missing, malformed, or expired staff access token",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "authenticated, but the user's roles do not allow this action",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/staff/visits": {
            "get": {
                "description": "Every projected journey, freshest sync first — the same per-visit shape as the single-journey read. Reads the CarePath projection only; a visit not yet ingested is absent until its first fact lands.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "List visits for the staff monitor",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/journey.View"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Liveness probe for the API.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "analytics.Overview": {
            "type": "object",
            "properties": {
                "asOf": {
                    "type": "string"
                },
                "servicePoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analytics.ServicePointMetrics"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/analytics.Summary"
                },
                "window": {
                    "type": "string"
                }
            }
        },
        "analytics.ServicePointMetrics": {
            "type": "object",
            "properties": {
                "avgServiceMinutes": {
                    "type": "number"
                },
                "avgWaitMinutes": {
                    "type": "number"
                },
                "code": {
                    "type": "string"
                },
                "completedCount": {
                    "type": "integer"
                },
                "inProgressNow": {
                    "type": "integer"
                },
                "longestWaitingMinutes": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "servicePointId": {
                    "type": "string"
                },
                "waitingNow": {
                    "type": "integer"
                }
            }
        },
        "analytics.Summary": {
            "type": "object",
            "properties": {
                "activeVisits": {
                    "type": "integer"
                },
                "avgVisitMinutes": {
                    "type": "number"
                },
                "avgWaitMinutes": {
                    "type": "number"
                },
                "bottleneckServicePointId": {
                    "type": "string"
                }
            }
        },
        "auth.identityResponse": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "userId": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.loginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.refreshRequest": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "auth.tokensResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "expiresAt": {
                    "type": "string"
                },
                "identity": {
                    "$ref": "#/definitions/auth.identityResponse"
                },
                "refreshExpiresAt": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "hospitalmap.Floor": {
            "type": "object",
            "properties": {
                "buildingId": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "levelOrder": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "hospitalmap.Place": {
            "type": "object",
            "properties": {
                "entryNodeId": {
                    "type": "string"
                },
                "floor": {
                    "$ref": "#/definitions/hospitalmap.Floor"
                },
                "floorId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        },
        "httpx.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "not_found"
                },
                "error": {
                    "type": "string",
                    "example": "visit not found"
                }
            }
        },
        "journey.PlanningExample": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "scenario": {
                    "$ref": "#/definitions/journey.PlanningExampleScenario"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/journey.PlanningExampleStep"
                    }
                }
            }
        },
        "journey.PlanningExampleOrder": {
            "type": "object",
            "properties": {
                "orderRef": {
                    "type": "string"
                },
                "orderType": {
                    "type": "string"
                },
                "orderedByClinic": {
                    "type": "string"
                }
            }
        },
        "journey.PlanningExampleScenario": {
            "type": "object",
            "properties": {
                "clinics": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "orders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/journey.PlanningExampleOrder"
                    }
                },
                "visitType": {
                    "type": "string"
                }
            }
        },
        "journey.PlanningExampleStep": {
            "type": "object",
            "properties": {
                "clinicCode": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "orderRefs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "round": {
                    "type": "integer"
                },
                "sequence": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "stepKey": {
                    "type": "string"
                }
            }
        },
        "journey.PlanningOrderType": {
            "type": "object",
            "properties": {
                "orderType": {
                    "type": "string"
                },
                "stepKind": {
                    "type": "string"
                }
            }
        },
        "journey.PlanningPhase": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                }
            }
        },
        "journey.PlanningRules": {
            "type": "object",
            "properties": {
                "examples": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/journey.PlanningExample"
                    }
                },
                "orderTypes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/journey.PlanningOrderType"
                    }
                },
                "phases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/journey.PlanningPhase"
                    }
                }
            }
        },
        "journey.QueueStep": {
            "type": "object",
            "properties": {
                "avgWaitMinutes": {
                    "type": "number"
                },
                "estimatedWaitMinutes": {
                    "type": "number"
                },
                "servicePointId": {
                    "type": "string"
                },
                "stepKey": {
                    "type": "string"
                },
                "waitingAhead": {
                    "type": "integer"
                }
            }
        },
        "journey.QueueView": {
            "type": "object",
            "properties": {
                "asOf": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/journey.QueueStep"
                    }
                },
                "visitId": {
                    "type": "string"
                }
            }
        },
        "journey.StepView": {
            "type": "object",
            "properties": {
                "clinicCode": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "orderRefs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "round": {
                    "type": "integer"
                },
                "sequence": {
                    "type": "integer"
                },
                "servicePoint": {
                    "$ref": "#/definitions/servicepoint.ServicePoint"
                },
                "servicePointId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "stepKey": {
                    "type": "string"
                }
            }
        },
        "journey.View": {
            "type": "object",
            "properties": {
                "actionable": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/journey.StepView"
                    }
                },
                "completed": {
                    "type": "boolean"
                },
                "patientName": {
                    "type": "string"
                },
                "patientRef": {
                    "type": "string"
                },
                "recommended": {
                    "$ref": "#/definitions/journey.StepView"
                },
                "status": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/journey.StepView"
                    }
                },
                "syncedAt": {
                    "type": "string"
                },
                "visitId": {
                    "type": "string"
                }
            }
        },
        "journey.transitionRequestBody": {
            "type": "object",
            "properties": {
                "commandId": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "location.Observation": {
            "type": "object",
            "properties": {
                "confidence": {
                    "type": "number"
                },
                "floorId": {
                    "type": "string"
                },
                "nodeId": {
                    "type": "string"
                },
                "observedAt": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/location.Source"
                },
                "visitId": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "location.Source": {
            "type": "string",
            "enum": [
                "QR",
                "ZIGBEE",
                "MANUAL"
            ],
            "x-enum-comments": {
                "SourceManual": "fallback/debug: a human-picked node",
                "SourceQR": "MVP baseline: a scanned CarePath QR code",
                "SourceZigbee": "phase 2: positioning service over Zigbee tags"
            },
            "x-enum-varnames": [
                "SourceQR",
                "SourceZigbee",
                "SourceManual"
            ]
        },
        "location.reportRequestBody": {
            "type": "object",
            "properties": {
                "raw": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "location.zigbeeSimulatorRequestBody": {
            "type": "object",
            "properties": {
                "confidence": {
                    "type": "number"
                },
                "floorId": {
                    "type": "string"
                },
                "visitId": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "main.HealthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "example": "carepath-api"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "navigation.NavEdge": {
            "type": "object",
            "properties": {
                "accessible": {
                    "type": "boolean"
                },
                "distance": {
                    "type": "number"
                },
                "edgeType": {
                    "description": "CORRIDOR, ELEVATOR, STAIRS",
                    "type": "string"
                },
                "fromNodeId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "toNodeId": {
                    "type": "string"
                }
            }
        },
        "navigation.NavNode": {
            "type": "object",
            "properties": {
                "floorId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nodeType": {
                    "description": "ENTRANCE, PLACE_ENTRY, CORRIDOR, ELEVATOR, STAIRS",
                    "type": "string"
                },
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "navigation.Route": {
            "type": "object",
            "properties": {
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/navigation.NavNode"
                    }
                },
                "segments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/navigation.NavEdge"
                    }
                },
                "totalDistance": {
                    "type": "number"
                }
            }
        },
        "servicepoint.ServicePoint": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "place": {
                    "$ref": "#/definitions/hospitalmap.Place"
                },
                "placeId": {
                    "type": "string"
                }
            }
        },
        "session.createRequest": {
            "type": "object",
            "properties": {
                "idToken": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "session.createResponse": {
            "type": "object",
            "properties": {
                "expiresAt": {
                    "type": "string"
                },
                "identity": {
                    "$ref": "#/definitions/session.identityResponse"
                },
                "sessionToken": {
                    "type": "string"
                }
            }
        },
        "session.identityResponse": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "externalId": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "share.LinkSecret": {
            "type": "object",
            "properties": {
                "expiresAt": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "share.SharedJourney": {
            "type": "object",
            "properties": {
                "currentStep": {
                    "$ref": "#/definitions/share.SharedStep"
                },
                "expiresAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "share.SharedStep": {
            "type": "object",
            "properties": {
                "floorName": {
                    "type": "string"
                },
                "servicePointName": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "CarePath API",
	Description:      "Patient journey and indoor navigation API above the HIS.\nServes the CarePath-derived journey plan (ADR-0009) with\nevery actionable step resolved to its service point.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
