// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/session": {
            "get": {
                "description": "Resolves the Authorization: Bearer session token to the identity behind it.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get the current session identity",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.identityResponse"
                        }
                    },
                    "401": {
                        "description": "session not found or expired",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Exchanges a LINE ID token (or, when enabled, a demo identity) for an opaque CarePath session token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Create a patient session",
                "parameters": [
                    {
                        "description": "source: line|demo, idToken: the LINE ID token (ignored for demo)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.createRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.createResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "invalid identity token, or demo auth disabled",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/journeys/{visitId}": {
            "get": {
                "description": "Returns the CarePath-derived journey plan (ADR-0009): steps in display order, each resolved to its service point, with every currently-actionable step and CarePath's recommendation among them. A completed visit is reported with completed=true and no actionable steps.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "journeys"
                ],
                "summary": "Get the patient journey",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit ID",
                        "name": "visitId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/journey.View"
                        }
                    },
                    "404": {
                        "description": "no journey projected for this visit",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/journeys/{visitId}/clinics/{clinicCode}/close-round": {
            "post": {
                "description": "Staff override (ADR-0009 §4): confirms the visit's latest round at this clinic is finished, dropping any not-yet-started inferred return, without waiting for the HIS's encounter.completed fact.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "journeys"
                ],
                "summary": "Close a clinic round",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit ID",
                        "name": "visitId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Clinic code",
                        "name": "clinicCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/journey.View"
                        }
                    },
                    "404": {
                        "description": "visit not found, journey not projected, or no open round at this clinic",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/journeys/{visitId}/location": {
            "get": {
                "description": "The latest recorded location observation of the visit (QR scan, Zigbee fix, manual pick) — the canonical start point for routing.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Get the visit's current location",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit ID",
                        "name": "visitId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/location.Observation"
                        }
                    },
                    "404": {
                        "description": "no location recorded for this visit yet",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Records a location fix for the visit and makes it the current location. The raw payload is the scanned string (a CarePath location QR carries a place reference only — never patient data); the server resolves it through the matching provider to a canonical navigation node and returns the recorded observation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Report a scanned location fix",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit ID",
                        "name": "visitId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Scanned fix: source (e.g. QR) and raw payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/location.reportRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/location.Observation"
                        }
                    },
                    "400": {
                        "description": "invalid body, unknown source, or a fix that does not resolve to a known location",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/journeys/{visitId}/steps/{stepKey}/transition": {
            "post": {
                "description": "Staff command that sets one step's status directly (ADR-0009 — CarePath owns step status; never forwarded to the HIS) and returns the refreshed journey with the plan recomputed. commandId is an optional idempotency key; source names the acting surface for the audit trail.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "journeys"
                ],
                "summary": "Transition one step",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit ID",
                        "name": "visitId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Step key",
                        "name": "stepKey",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Transition command",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/journey.transitionRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/journey.View"
                        }
                    },
                    "400": {
                        "description": "invalid body or unknown target status",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "visit or step not found, or journey not projected",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "illegal transition",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "upstream HIS error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/service-points": {
            "get": {
                "description": "Active service points with their resolved place and floor — the service → destination mapping patients navigate by and staff see in the console.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service-points"
                ],
                "summary": "List service points",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/servicepoint.ServicePoint"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/service-points/{code}": {
            "get": {
                "description": "One active service point (e.g. code LAB) with its resolved place and floor — the destination lookup for a care step's service code.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service-points"
                ],
                "summary": "Get a service point by code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service code (e.g. REGISTRATION, DOCTOR, LAB, XRAY, PHARMACY)",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/servicepoint.ServicePoint"
                        }
                    },
                    "404": {
                        "description": "service point not found",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/staff/visits": {
            "get": {
                "description": "Every projected journey, freshest sync first — the same per-visit shape as the single-journey read. Reads the CarePath projection only; a visit not yet ingested is absent until its first fact lands.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "staff"
                ],
                "summary": "List visits for the staff monitor",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/journey.View"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Liveness probe for the API.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "hospitalmap.Floor": {
            "type": "object",
            "properties": {
                "buildingId": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "levelOrder": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "hospitalmap.Place": {
            "type": "object",
            "properties": {
                "entryNodeId": {
                    "type": "string"
                },
                "floor": {
                    "$ref": "#/definitions/hospitalmap.Floor"
                },
                "floorId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        },
        "httpx.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "visit not found"
                }
            }
        },
        "journey.StepView": {
            "type": "object",
            "properties": {
                "clinicCode": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "orderRefs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "round": {
                    "type": "integer"
                },
                "sequence": {
                    "type": "integer"
                },
                "servicePoint": {
                    "$ref": "#/definitions/servicepoint.ServicePoint"
                },
                "servicePointId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "stepKey": {
                    "type": "string"
                }
            }
        },
        "journey.View": {
            "type": "object",
            "properties": {
                "actionable": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/journey.StepView"
                    }
                },
                "completed": {
                    "type": "boolean"
                },
                "patientName": {
                    "type": "string"
                },
                "patientRef": {
                    "type": "string"
                },
                "recommended": {
                    "$ref": "#/definitions/journey.StepView"
                },
                "status": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/journey.StepView"
                    }
                },
                "syncedAt": {
                    "type": "string"
                },
                "visitId": {
                    "type": "string"
                }
            }
        },
        "journey.transitionRequestBody": {
            "type": "object",
            "properties": {
                "commandId": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "location.Observation": {
            "type": "object",
            "properties": {
                "confidence": {
                    "type": "number"
                },
                "floorId": {
                    "type": "string"
                },
                "nodeId": {
                    "type": "string"
                },
                "observedAt": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/location.Source"
                },
                "visitId": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "location.Source": {
            "type": "string",
            "enum": [
                "QR",
                "ZIGBEE",
                "MANUAL"
            ],
            "x-enum-comments": {
                "SourceManual": "fallback/debug: a human-picked node",
                "SourceQR": "MVP baseline: a scanned CarePath QR code",
                "SourceZigbee": "phase 2: positioning service over Zigbee tags"
            },
            "x-enum-varnames": [
                "SourceQR",
                "SourceZigbee",
                "SourceManual"
            ]
        },
        "location.reportRequestBody": {
            "type": "object",
            "properties": {
                "raw": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "main.HealthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "example": "carepath-api"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "servicepoint.ServicePoint": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "place": {
                    "$ref": "#/definitions/hospitalmap.Place"
                },
                "placeId": {
                    "type": "string"
                }
            }
        },
        "session.createRequest": {
            "type": "object",
            "properties": {
                "idToken": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "session.createResponse": {
            "type": "object",
            "properties": {
                "expiresAt": {
                    "type": "string"
                },
                "identity": {
                    "$ref": "#/definitions/session.identityResponse"
                },
                "sessionToken": {
                    "type": "string"
                }
            }
        },
        "session.identityResponse": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "externalId": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "CarePath API",
	Description:      "Patient journey and indoor navigation API above the HIS.\nServes the CarePath-derived journey plan (ADR-0009) with\nevery actionable step resolved to its service point.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
