dsn: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable

docPath: docs/architecture/erd

include:
  - carepath.*

er:
  format: mermaid
  distance: 1
