/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignRouteImport } from './routes/design'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as PatientJourneyRouteImport } from './routes/patient/journey'
import { Route as PatientNavigateRouteImport } from './routes/patient/navigate'
import { Route as StaffFloorPlanRouteImport } from './routes/staff/floor-plan'
import { Route as StaffOverviewRouteImport } from './routes/staff/overview'
import { Route as StaffPathwayTemplatesRouteImport } from './routes/staff/pathway-templates'
import { Route as StaffPatientsRouteImport } from './routes/staff/patients'
import { Route as StaffQueueRouteImport } from './routes/staff/queue'
import { Route as StaffServicePointsRouteImport } from './routes/staff/service-points'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientJourneyRoute = PatientJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => PatientRoute,
} as any)
const PatientNavigateRoute = PatientNavigateRouteImport.update({
  id: '/navigate',
  path: '/navigate',
  getParentRoute: () => PatientRoute,
} as any)
const StaffFloorPlanRoute = StaffFloorPlanRouteImport.update({
  id: '/staff/floor-plan',
  path: '/staff/floor-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffOverviewRoute = StaffOverviewRouteImport.update({
  id: '/staff/overview',
  path: '/staff/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPathwayTemplatesRoute = StaffPathwayTemplatesRouteImport.update({
  id: '/staff/pathway-templates',
  path: '/staff/pathway-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPatientsRoute = StaffPatientsRouteImport.update({
  id: '/staff/patients',
  path: '/staff/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffQueueRoute = StaffQueueRouteImport.update({
  id: '/staff/queue',
  path: '/staff/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffServicePointsRoute = StaffServicePointsRouteImport.update({
  id: '/staff/service-points',
  path: '/staff/service-points',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/patient/journey': typeof PatientJourneyRoute
  '/patient/navigate': typeof PatientNavigateRoute
  '/staff/floor-plan': typeof StaffFloorPlanRoute
  '/staff/overview': typeof StaffOverviewRoute
  '/staff/pathway-templates': typeof StaffPathwayTemplatesRoute
  '/staff/patients': typeof StaffPatientsRoute
  '/staff/queue': typeof StaffQueueRoute
  '/staff/service-points': typeof StaffServicePointsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/patient/journey': typeof PatientJourneyRoute
  '/patient/navigate': typeof PatientNavigateRoute
  '/staff/floor-plan': typeof StaffFloorPlanRoute
  '/staff/overview': typeof StaffOverviewRoute
  '/staff/pathway-templates': typeof StaffPathwayTemplatesRoute
  '/staff/patients': typeof StaffPatientsRoute
  '/staff/queue': typeof StaffQueueRoute
  '/staff/service-points': typeof StaffServicePointsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/patient/journey': typeof PatientJourneyRoute
  '/patient/navigate': typeof PatientNavigateRoute
  '/staff/floor-plan': typeof StaffFloorPlanRoute
  '/staff/overview': typeof StaffOverviewRoute
  '/staff/pathway-templates': typeof StaffPathwayTemplatesRoute
  '/staff/patients': typeof StaffPatientsRoute
  '/staff/queue': typeof StaffQueueRoute
  '/staff/service-points': typeof StaffServicePointsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/login'
    | '/patient'
    | '/patient/journey'
    | '/patient/navigate'
    | '/staff/floor-plan'
    | '/staff/overview'
    | '/staff/pathway-templates'
    | '/staff/patients'
    | '/staff/queue'
    | '/staff/service-points'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/login'
    | '/patient'
    | '/patient/journey'
    | '/patient/navigate'
    | '/staff/floor-plan'
    | '/staff/overview'
    | '/staff/pathway-templates'
    | '/staff/patients'
    | '/staff/queue'
    | '/staff/service-points'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/login'
    | '/patient'
    | '/patient/journey'
    | '/patient/navigate'
    | '/staff/floor-plan'
    | '/staff/overview'
    | '/staff/pathway-templates'
    | '/staff/patients'
    | '/staff/queue'
    | '/staff/service-points'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRouteWithChildren
  StaffFloorPlanRoute: typeof StaffFloorPlanRoute
  StaffOverviewRoute: typeof StaffOverviewRoute
  StaffPathwayTemplatesRoute: typeof StaffPathwayTemplatesRoute
  StaffPatientsRoute: typeof StaffPatientsRoute
  StaffQueueRoute: typeof StaffQueueRoute
  StaffServicePointsRoute: typeof StaffServicePointsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/journey': {
      id: '/patient/journey'
      path: '/journey'
      fullPath: '/patient/journey'
      preLoaderRoute: typeof PatientJourneyRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/navigate': {
      id: '/patient/navigate'
      path: '/navigate'
      fullPath: '/patient/navigate'
      preLoaderRoute: typeof PatientNavigateRouteImport
      parentRoute: typeof PatientRoute
    }
    '/staff/floor-plan': {
      id: '/staff/floor-plan'
      path: '/staff/floor-plan'
      fullPath: '/staff/floor-plan'
      preLoaderRoute: typeof StaffFloorPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/overview': {
      id: '/staff/overview'
      path: '/staff/overview'
      fullPath: '/staff/overview'
      preLoaderRoute: typeof StaffOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/pathway-templates': {
      id: '/staff/pathway-templates'
      path: '/staff/pathway-templates'
      fullPath: '/staff/pathway-templates'
      preLoaderRoute: typeof StaffPathwayTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/patients': {
      id: '/staff/patients'
      path: '/staff/patients'
      fullPath: '/staff/patients'
      preLoaderRoute: typeof StaffPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/queue': {
      id: '/staff/queue'
      path: '/staff/queue'
      fullPath: '/staff/queue'
      preLoaderRoute: typeof StaffQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/service-points': {
      id: '/staff/service-points'
      path: '/staff/service-points'
      fullPath: '/staff/service-points'
      preLoaderRoute: typeof StaffServicePointsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PatientRouteChildren {
  PatientJourneyRoute: typeof PatientJourneyRoute
  PatientNavigateRoute: typeof PatientNavigateRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientJourneyRoute: PatientJourneyRoute,
  PatientNavigateRoute: PatientNavigateRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRouteWithChildren,
  StaffFloorPlanRoute: StaffFloorPlanRoute,
  StaffOverviewRoute: StaffOverviewRoute,
  StaffPathwayTemplatesRoute: StaffPathwayTemplatesRoute,
  StaffPatientsRoute: StaffPatientsRoute,
  StaffQueueRoute: StaffQueueRoute,
  StaffServicePointsRoute: StaffServicePointsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
