/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/{visitId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Normalized visit view: the HIS visit enriched with the first READY step and its configured service point, if any. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    visitId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Normalized visit view */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VisitView"];
                    };
                };
                /** @description Visit not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Upstream HIS error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/{visitId}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The next actionable (READY) step, resolved to its service point. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    visitId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Next actionable step */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NextStep"];
                    };
                };
                /** @description No next actionable step, or visit not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Upstream HIS error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Resolves the Authorization Bearer session token to the identity behind it. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current session identity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Identity"];
                    };
                };
                /** @description Session not found or expired */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** @description Exchanges a LINE ID token (source "line"), or a demo identity (source "demo", only when the server has ALLOW_DEMO_AUTH enabled), for an opaque CarePath session token. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSessionRequest"];
                };
            };
            responses: {
                /** @description Session created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateSessionResponse"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Invalid identity token, or demo auth disabled */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journeys/{visitId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The patient journey: the CarePath-owned projection of the HIS visit (ADR-0008), with steps ordered by sequence and the deterministic current/next step resolution. A visit not yet projected (ingest lag) returns 404. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    visitId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The projected journey */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Journey"];
                    };
                };
                /** @description No journey projected for this visit id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/navigation/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Not implemented yet — reserved for the navigation module. */
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Navigation route */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        /** @description A care step as reported by the HIS. */
        VisitStep: {
            sequence: number;
            serviceCode: string;
            /** @description HIS step status, e.g. COMPLETED, READY, PENDING. */
            status: string;
        };
        /** @description A visit as reported by the HIS. */
        Visit: {
            visitId: string;
            patientRef: string;
            /** @description HIS visit status, e.g. ACTIVE. */
            status: string;
            steps: components["schemas"]["VisitStep"][];
        };
        /** @description Links a service code to a physical Place in the hospital map. */
        ServicePoint: {
            id: string;
            code: string;
            name: string;
            placeId: string;
        };
        /** @description The first READY step of a visit, resolved to its service point when one is configured for the step's service code. */
        NextStep: {
            sequence: number;
            status: string;
            servicePoint?: components["schemas"]["ServicePoint"];
        };
        /** @description One care step of the journey projection, resolved to its configured service point when one exists. */
        JourneyStep: {
            sequence: number;
            /** @description External service code in HIS vocabulary (e.g. LAB). */
            serviceCode: string;
            /** @description Canonical step status (PENDING, READY, STARTED, COMPLETED, CANCELLED). */
            status: string;
            /** @description Bound service point id; null when no service point is configured for the code (explicit unmapped state). */
            servicePointId: string | null;
            /** @description The bound service point, when configured and still active. */
            servicePoint?: components["schemas"]["ServicePoint"] | null;
        };
        /** @description The projected journey of one HIS visit with deterministic current/next step resolution. */
        Journey: {
            visitId: string;
            patientRef: string;
            /**
             * @description Canonical visit status.
             * @enum {string}
             */
            status: "ACTIVE" | "COMPLETED" | "CANCELLED";
            /** @description True iff the visit status is COMPLETED — the unambiguous finished signal; current and next are null in that case. */
            completed: boolean;
            /** @description All steps of the visit ordered by sequence. */
            steps: components["schemas"]["JourneyStep"][];
            /** @description The first STARTED step by sequence, if any. */
            current?: components["schemas"]["JourneyStep"] | null;
            /** @description The first READY step by sequence — the next actionable step, if any. */
            next?: components["schemas"]["JourneyStep"] | null;
            /** Format: date-time */
            syncedAt: string;
        };
        /** @description The Visit fields plus the resolved next step. */
        VisitView: {
            visitId: string;
            patientRef: string;
            status: string;
            steps: components["schemas"]["VisitStep"][];
            next?: components["schemas"]["NextStep"];
        };
        /** @description A verified external identity behind a CarePath session. */
        Identity: {
            /** @enum {string} */
            source: "line" | "demo";
            externalId: string;
            displayName?: string;
        };
        CreateSessionRequest: {
            /** @enum {string} */
            source: "line" | "demo";
            /** @description The LINE ID token. Ignored (may be empty) for source "demo". */
            idToken: string;
        };
        CreateSessionResponse: {
            sessionToken: string;
            identity: components["schemas"]["Identity"];
            /** Format: date-time */
            expiresAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
