/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/{visitId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Normalized visit view: the HIS visit enriched with the first READY step and its configured service point, if any. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    visitId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Normalized visit view */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VisitView"];
                    };
                };
                /** @description Visit not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Upstream HIS error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/{visitId}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The next actionable (READY) step, resolved to its service point. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    visitId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Next actionable step */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NextStep"];
                    };
                };
                /** @description No next actionable step, or visit not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Upstream HIS error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/navigation/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Not implemented yet — reserved for the navigation module. */
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Navigation route */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        /** @description A care step as reported by the HIS. */
        VisitStep: {
            sequence: number;
            serviceCode: string;
            /** @description HIS step status, e.g. COMPLETED, READY, PENDING. */
            status: string;
        };
        /** @description A visit as reported by the HIS. */
        Visit: {
            visitId: string;
            patientRef: string;
            /** @description HIS visit status, e.g. ACTIVE. */
            status: string;
            steps: components["schemas"]["VisitStep"][];
        };
        /** @description Links a service code to a physical Place in the hospital map. */
        ServicePoint: {
            id: string;
            code: string;
            name: string;
            placeId: string;
        };
        /** @description The first READY step of a visit, resolved to its service point when one is configured for the step's service code. */
        NextStep: {
            sequence: number;
            status: string;
            servicePoint?: components["schemas"]["ServicePoint"];
        };
        /** @description The Visit fields plus the resolved next step. */
        VisitView: {
            visitId: string;
            patientRef: string;
            status: string;
            steps: components["schemas"]["VisitStep"][];
            next?: components["schemas"]["NextStep"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
